image: jelaniwoods/appdev2021-rps-html@sha256:805be22ba86b3ce17116f6dfa2f020814b53a58831c6374c0bbe3b2fdb347c6c

tasks:
  - init: bin/setup
ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - shd101wyy.markdown-preview-enhanced
    - vortizhe.simple-ruby-erb
    - CraigMaslowski.erb
    - Vense.rails-snippets
    - wingrunr21.vscode-ruby
